<a href="https://colab.research.google.com/github/capabledjay/Deep_Learning_With_Pytorch/blob/main/pytorch_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Pytorch Fundamentals

Resourse notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/


In [22]:
!nvidia-smi


/bin/bash: nvidia-smi: command not found


In [23]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


## Introduction to Tensors
Tensors are the fundamental building block of machine learning.
Their job is to represent data in a numerical way. For example, you could represent an image as a tensor with shape [3, 224, 224] which would mean [colour_channels, height, width], as in the image has 3 colour channels (red, green, blue), a height of 224 pixels and a width of 224 pixels.

### Creating tensors


##### Scalar
A scalar is a single number and in tensor-speak it's a zero dimension tensor.
####

In [24]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [25]:
# to check for the dimension of the tensor
scalar.ndim

0

In [26]:
# Get tensor back as a Py int
scalar.item()

7

### vector.
A vector is a single dimension tensor but can contain many numbers.
As in, you could have a vector [3, 2] to describe [bedrooms, bathrooms] in your house. Or you could have [3, 2, 2] to describe [bedrooms, bathrooms, car_parks] in your house.
The important trend here is that a vector is flexible in what it can represent (the same with tensors).

In [27]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [28]:
# Check the number of dimensions of vector
vector.ndim

1

You can tell the number of dimensions a tensor in PyTorch has by the number of square brackets on the outside ([) and you only need to count one side.

Another important concept for tensors is their shape attribute. The shape tells you how the elements inside them are arranged.

In [29]:
# Check shape of vector
vector.shape

torch.Size([2])

In [30]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

Matrices are as flexible as vectors, except they've got an extra dimension.

In [31]:
# Check number of dimensions
MATRIX.ndim

2

In [32]:
MATRIX.shape

torch.Size([2, 2])

In [34]:
 # Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [35]:
# Check number of dimensions for TENSOR
TENSOR.ndim

3

In [36]:
# Check shape of TENSOR
TENSOR.shape

torch.Size([1, 3, 3])

Alright, it outputs torch.Size([1, 3, 3]).

The dimensions go outer to inner.

That means there's 1 dimension of 3 by 3.